apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: saferworld-api
  namespace: saferworld
spec:
  interval: 30m
  chart:
    spec:
      chart: ushahidi-platform-api
      version: ">=0.0.1-alpha.36"
      sourceRef:
        kind: HelmRepository
        name: ushahidi
      interval: 1h
  valuesFrom:
    - kind: Secret
      name: saferworld-db-credentials
      valuesKey: host
      targetPath: config.db.host
    - kind: Secret
      name: saferworld-db-credentials
      valuesKey: username
      targetPath: config.db.username
    - kind: Secret
      name: saferworld-db-credentials
      valuesKey: password
      targetPath: config.db.password
    - kind: Secret
      name: saferworld-db-credentials
      valuesKey: database
      targetPath: config.db.database
  values:
    image:
      repository: ghcr.io/howtobuildup
      name: platform
      tag: "1.0.2"
    config:
      appenv: production
      timezone: UTC
      db:
        port: 3306
      redis:
        host: redis
        port: 6379
      drivers:
        cache: redis
        ratelimiter_cache: redis
        queue: redis
    api:
      replicas: 1
      debug: "False"
      ingress:
        enabled: true
        annotations:
          cert-manager.io/issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-body-size: "60m"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
        host: api.app.saferworld-ogaal.org
        tls:
          - secretName: saferworld-api-tls
            hosts:
              - api.app.saferworld-ogaal.org
    worker:
      replicas: 1
    mysql:
      enabled: false
    redis:
      enabled: true
