apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: saferworld
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@howtobuildup.org
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
